name: mmf
description: Mahalla Members Form
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700